services:
  - type: web
    name: askmydocs-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: ELASTIC_CLOUD_ID
        sync: false
      - key: ELASTIC_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX
        sync: false
      - key: GEMINI_API_KEY
        sync: false
